---

jwt:
  secret: mysecret


  # mail sender config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngankemlaurence@gmail.com
    password: qanwxizaquorxzbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  datasource:
    url: jdbc:mysql://10.0.2.6:3306/kulvida
    username: backend
    password: root



  jpa:
    hibernate:
      ddl-auto: update

    ## Hibernate Properties
    ## The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect


#paypal config
paypal:
  mode: sandbox
  client:
    id: AWMpiyTMvENb5KJz3R15RXHlUGObbD50SFvl6Ng7DfZLcW_oYx6LC6GckgkJwI7hQE5u-KvCWnIs_Kx4
    secret: EFZpWc2g9btWzM6z46GI1jCeAlxo9sQJhCHLTdNKqNOt_2cF9OQ8Tx9mr-pmHG4V6LMLSDint3a3cpmL



