---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kulvida
    username: root
    password: root

logging:
  file:
    path: C:/Users/Quentin/Desktop/testGit/logs/
    name: kulvida.log
  level:
    root: INFO

  logback:
    rollingpolicy:
      file-name-pattern: C:/Users/Quentin/Desktop/testGit/logs/kulvida.%d{yyyy-MM-dd}.%i.log
  
  